// <auto-generated />
using System;
using ApiRest.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRest.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240527164332_vengaya")]
    partial class vengaya
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRest.Models.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Etiqueta");
                });

            modelBuilder.Entity("ApiRest.Models.Juego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accesible_M")
                        .HasColumnType("bit");

                    b.Property<bool>("Accesible_PC")
                        .HasColumnType("bit");

                    b.Property<string>("Compania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Descuento")
                        .HasColumnType("real");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Juego");
                });

            modelBuilder.Entity("ApiRest.Models.JuegoXEtiqueta", b =>
                {
                    b.Property<int>("IdJuego")
                        .HasColumnType("int");

                    b.Property<int>("IdEtiqueta")
                        .HasColumnType("int");

                    b.HasKey("IdJuego", "IdEtiqueta");

                    b.HasIndex("IdEtiqueta");

                    b.ToTable("JuegoXEtiqueta");
                });

            modelBuilder.Entity("ApiRest.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("ApiRest.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Dinero")
                        .HasColumnType("real");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiRest.Models.UsuarioXJuego", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdJuego")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdJuego");

                    b.HasIndex("IdJuego");

                    b.ToTable("UsuarioXJuego");
                });

            modelBuilder.Entity("ApiRest.Models.JuegoXEtiqueta", b =>
                {
                    b.HasOne("ApiRest.Models.Etiqueta", "EtiquetaFK")
                        .WithMany("JuegoXEtiquetas")
                        .HasForeignKey("IdEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Juego", "JuegoFK")
                        .WithMany("JuegoXEtiquetas")
                        .HasForeignKey("IdJuego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtiquetaFK");

                    b.Navigation("JuegoFK");
                });

            modelBuilder.Entity("ApiRest.Models.Usuario", b =>
                {
                    b.HasOne("ApiRest.Models.Rol", "RolFK")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId");

                    b.Navigation("RolFK");
                });

            modelBuilder.Entity("ApiRest.Models.UsuarioXJuego", b =>
                {
                    b.HasOne("ApiRest.Models.Juego", "JuegoFK")
                        .WithMany("UsuarioXJuego")
                        .HasForeignKey("IdJuego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiRest.Models.Usuario", "UsuarioFK")
                        .WithMany("UsuarioXJuego")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JuegoFK");

                    b.Navigation("UsuarioFK");
                });

            modelBuilder.Entity("ApiRest.Models.Etiqueta", b =>
                {
                    b.Navigation("JuegoXEtiquetas");
                });

            modelBuilder.Entity("ApiRest.Models.Juego", b =>
                {
                    b.Navigation("JuegoXEtiquetas");

                    b.Navigation("UsuarioXJuego");
                });

            modelBuilder.Entity("ApiRest.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiRest.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioXJuego");
                });
#pragma warning restore 612, 618
        }
    }
}
